// Code generated by counterfeiter. DO NOT EDIT.
package libraryTest

import (
	"counterfeiterTest/foo"
	"sync"
)

type FakeMySpecialInterface4 struct {
	DoThings2Stub        func(string, uint64) (int, error)
	doThings2Mutex       sync.RWMutex
	doThings2ArgsForCall []struct {
		arg1 string
		arg2 uint64
	}
	doThings2Returns struct {
		result1 int
		result2 error
	}
	doThings2ReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMySpecialInterface4) DoThings2(arg1 string, arg2 uint64) (int, error) {
	fake.doThings2Mutex.Lock()
	ret, specificReturn := fake.doThings2ReturnsOnCall[len(fake.doThings2ArgsForCall)]
	fake.doThings2ArgsForCall = append(fake.doThings2ArgsForCall, struct {
		arg1 string
		arg2 uint64
	}{arg1, arg2})
	stub := fake.DoThings2Stub
	fakeReturns := fake.doThings2Returns
	fake.recordInvocation("DoThings2", []interface{}{arg1, arg2})
	fake.doThings2Mutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMySpecialInterface4) DoThings2CallCount() int {
	fake.doThings2Mutex.RLock()
	defer fake.doThings2Mutex.RUnlock()
	return len(fake.doThings2ArgsForCall)
}

func (fake *FakeMySpecialInterface4) DoThings2Calls(stub func(string, uint64) (int, error)) {
	fake.doThings2Mutex.Lock()
	defer fake.doThings2Mutex.Unlock()
	fake.DoThings2Stub = stub
}

func (fake *FakeMySpecialInterface4) DoThings2ArgsForCall(i int) (string, uint64) {
	fake.doThings2Mutex.RLock()
	defer fake.doThings2Mutex.RUnlock()
	argsForCall := fake.doThings2ArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMySpecialInterface4) DoThings2Returns(result1 int, result2 error) {
	fake.doThings2Mutex.Lock()
	defer fake.doThings2Mutex.Unlock()
	fake.DoThings2Stub = nil
	fake.doThings2Returns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeMySpecialInterface4) DoThings2ReturnsOnCall(i int, result1 int, result2 error) {
	fake.doThings2Mutex.Lock()
	defer fake.doThings2Mutex.Unlock()
	fake.DoThings2Stub = nil
	if fake.doThings2ReturnsOnCall == nil {
		fake.doThings2ReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.doThings2ReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeMySpecialInterface4) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.doThings2Mutex.RLock()
	defer fake.doThings2Mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMySpecialInterface4) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ foo.MySpecialInterface4 = new(FakeMySpecialInterface4)
